lea:
  modulesDir: ../modules

  allowlist:
    senders:
      - "+4912345678"
      - "+4911111111"
    groups:
      - "GROUP_ID_EXAMPLE"

  signal:
    rpcUrl: "http://127.0.0.1:8080/api/v1/rpc"
    eventsUrl: "http://127.0.0.1:8080/api/v1/events"
    account: "+49DEINACCOUNT"
